"""password -> hashed_password

Revision ID: 4df897da1bc3
Revises: 8c39c71a704b
Create Date: 2026-06-22 11:49:03.189291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4df897da1bc3'
down_revision: Union[str, Sequence[str], None] = '8c39c71a704b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("usersdb",column_name="password",new_column_name="hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersdb', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('usersdb', 'hashed_password')
    # ### end Alembic commands ###
