"""user_name set to unique

Revision ID: 87b8a47e176c
Revises: a1f3cef1ec3e
Create Date: 2026-06-23 21:04:55.628078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b8a47e176c'
down_revision: Union[str, Sequence[str], None] = 'a1f3cef1ec3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usersdb', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usersdb', type_='unique')
    # ### end Alembic commands ###
