"""posts.user_id ON DELETE CASCADE

Revision ID: a1f3cef1ec3e
Revises: a5787f214ae3
Create Date: 2026-06-23 11:35:38.512527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f3cef1ec3e'
down_revision: Union[str, Sequence[str], None] = 'a5787f214ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_user_id_fkey'), 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'usersdb', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(op.f('post_user_id_fkey'), 'post', 'usersdb', ['user_id'], ['id'])
    # ### end Alembic commands ###
