"""add column 'disabled'

Revision ID: a5787f214ae3
Revises: 4df897da1bc3
Create Date: 2026-06-22 12:03:06.720157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5787f214ae3'
down_revision: Union[str, Sequence[str], None] = '4df897da1bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersdb', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersdb', 'disabled')
    # ### end Alembic commands ###
