"""Make email unique in users.models.UserBase

Revision ID: d42fcea69382
Revises: 59e0eb56d98e
Create Date: 2026-07-01 15:19:15.668896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42fcea69382'
down_revision: Union[str, Sequence[str], None] = '59e0eb56d98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usersdb', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usersdb', type_='unique')
    # ### end Alembic commands ###
